volumes:
  todo-core-db:
    driver: local
  auth-db:
    driver: local
  todo-comments-db:
    driver: local


services:
  core:
    stop_grace_period: 1s
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./todo-core:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - main
    depends_on:
      - todo-core-db
  todo-core-db:
    image: postgres
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todos
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - todo-core-db:/var/lib/postgresql/data
    networks:
      - main
  auth:
    stop_grace_period: 1s
    build: .
    ports:
      - 8081:8080
    volumes:
      - ./auth:/app
    networks:
      - main
    depends_on:
      - auth-db
  auth-db:
    image: postgres
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: auth
    ports:
      - 5433:5432
    expose:
      - 5432
    volumes:
      - auth-db:/var/lib/postgresql/data
    networks:
      - main
  comments:
    stop_grace_period: 1s
    build: .
    ports:
      - 8082:8080
    volumes:
      - ./todo-comments:/app
    networks:
      - main
    depends_on:
      - comments-db
  comments-db:
    image: postgres
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: comments
    ports:
      - 5434:5432
    expose:
      - 5432
    volumes:
      - todo-comments-db:/var/lib/postgresql/data
    networks:
      - main

networks:
  main:
    driver: bridge